name: 'Cosign bake metadata'
description:
  'Generate a list of container image digests from "docker/bake-action" metadata
  output'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  bake-targets:
    description: 'The targets to bake'
    required: false
  bake-metadata-output:
    description: "The metadata output from 'docker/bake-action'"
    required: true
  extract-platform-manifests:
    description: 'Extract platform manifests (Default: false)'
    required: false
    default: false

outputs:
  images:
    description: 'A list of container image digests'

runs:
  using: 'node20'
  main: 'dist/index.js'
